# Auto-generated by scripts/gen_shims.py — DO NOT EDIT BY HAND.
# Regenerate after `maturin develop` when the API changes.

# fastsim.solvers — Drop-in replacement for pathsim.solvers

from fastsim._fastsim import (
    SSPRK22 as _SSPRK22,
    SSPRK33 as _SSPRK33,
    SSPRK34 as _SSPRK34,
    RK4 as _RK4,
    EUF as _EUF,
    EUB as _EUB,
    RKF21 as _RKF21,
    RKBS32 as _RKBS32,
    RKF45 as _RKF45,
    RKCK54 as _RKCK54,
    RKDP54 as _RKDP54,
    RKV65 as _RKV65,
    RKF78 as _RKF78,
    RKDP87 as _RKDP87,
    DIRK2 as _DIRK2,
    DIRK3 as _DIRK3,
    ESDIRK4 as _ESDIRK4,
    ESDIRK32 as _ESDIRK32,
    ESDIRK43 as _ESDIRK43,
    ESDIRK54 as _ESDIRK54,
    GEAR52A as _GEAR52A,
    SteadyState as _SteadyState,
)

class SSPRK22(_SSPRK22):
    """
    Strong Stability Preserving Runge-Kutta, 2 stages, 2nd order (Heun). Explicit, fixed step; the default solver for non-stiff problems.
    """

class SSPRK33(_SSPRK33):
    """
    Strong Stability Preserving Runge-Kutta, 3 stages, 3rd order (Shu-Osher). Explicit, fixed step, non-stiff.
    """

class SSPRK34(_SSPRK34):
    """
    Strong Stability Preserving Runge-Kutta, 4 stages, 3rd order, with an enlarged stability region. Explicit, fixed step, non-stiff.
    """

class RK4(_RK4):
    """
    Classic Runge-Kutta, 4 stages, 4th order. Explicit, fixed step; a robust general-purpose non-stiff integrator.
    """

class EUF(_EUF):
    """
    Explicit (forward) Euler, 1st order. The simplest explicit integrator; fixed step, non-stiff.
    """

class EUB(_EUB):
    """
    Implicit (backward) Euler, 1st order. L-stable, fixed step; a robust choice for stiff problems.
    """

class RKF21(_RKF21):
    """
    Runge-Kutta-Fehlberg embedded pair, orders 2 and 1, for adaptive step-size control. Explicit, non-stiff.
    """

class RKBS32(_RKBS32):
    """
    Bogacki-Shampine embedded pair, orders 3 and 2 (the method behind MATLAB's ode23). Explicit, adaptive, non-stiff.
    """

class RKF45(_RKF45):
    """
    Runge-Kutta-Fehlberg embedded pair, orders 4 and 5, for adaptive step-size control. Explicit, non-stiff.
    """

class RKCK54(_RKCK54):
    """
    Cash-Karp embedded Runge-Kutta pair, orders 5 and 4, for adaptive step-size control. Explicit, non-stiff.
    """

class RKDP54(_RKDP54):
    """
    Dormand-Prince embedded Runge-Kutta pair, orders 5 and 4 (the method behind MATLAB's ode45). Explicit, adaptive; the default general-purpose non-stiff solver.
    """

class RKV65(_RKV65):
    """
    Verner embedded Runge-Kutta pair, orders 6 and 5, for adaptive step-size control. Explicit, non-stiff, higher accuracy.
    """

class RKF78(_RKF78):
    """
    Runge-Kutta-Fehlberg embedded pair, orders 7 and 8, for adaptive step-size control. Explicit, non-stiff, high accuracy.
    """

class RKDP87(_RKDP87):
    """
    Dormand-Prince embedded Runge-Kutta pair, orders 8 and 7, for adaptive step-size control. Explicit, non-stiff, very high accuracy.
    """

class DIRK2(_DIRK2):
    """
    Diagonally Implicit Runge-Kutta, 2nd order. L-stable; solves an implicit system per stage, for stiff problems.
    """

class DIRK3(_DIRK3):
    """
    Diagonally Implicit Runge-Kutta, 3rd order. L-stable, for stiff problems.
    """

class ESDIRK4(_ESDIRK4):
    """
    Explicit-first-stage Singly Diagonally Implicit Runge-Kutta, 4th order. Stiffly accurate and L-stable, for stiff problems.
    """

class ESDIRK32(_ESDIRK32):
    """
    Explicit-first-stage Singly Diagonally Implicit Runge-Kutta embedded pair, orders 3 and 2, for adaptive step-size control. L-stable, for stiff problems.
    """

class ESDIRK43(_ESDIRK43):
    """
    Explicit-first-stage Singly Diagonally Implicit Runge-Kutta embedded pair, orders 4 and 3, for adaptive step-size control. L-stable, for stiff problems.
    """

class ESDIRK54(_ESDIRK54):
    """
    Explicit-first-stage Singly Diagonally Implicit Runge-Kutta embedded pair, orders 5 and 4, for adaptive step-size control. L-stable, for stiff problems.
    """

class GEAR52A(_GEAR52A):
    """
    Gear-type backward differentiation formula (BDF) with adaptive order (up to 5) and adaptive step size. Multi-step and L-stable, for stiff problems.
    """

class SteadyState(_SteadyState):
    """
    Steady-state (DC operating point) solver. Finds the equilibrium of the system by root-finding on the residual rather than time integration.
    """
