"""Codegen across every emittable solver.

``test_codegen_clang_matrix.py`` pins the solver axis to ``rk4``/``euler``
because its trajectory check compares against a fixed-step reference. That left
the eight ADAPTIVE tableaus generated by nothing — and they emit a different
integrator entirely: an embedded error estimate, an accept/reject loop with the
I-controller, and a carried step size in the model struct. The editor's default
solver is adaptive, so the common case was the unchecked one.

This sweeps all thirteen, on every system including the subsystem topologies,
for the two contracts that do not need a reference trajectory:

1. **Generation** — ``to_c`` must not raise.
2. **Import contract** — every external function the emitted C calls has to be
   in the browser runner's import table, or the WASM module fails to
   instantiate with "function import requires a callable". A native compile
   cannot catch this because it links libm directly.

Adaptive trajectories are deliberately not compared here: the generated C
clamps every step to the recording grid while the reference steps freely, so
the two take different step sequences by construction. Verifying those is what
`Simulation.verify_c` refuses to do for adaptive solvers, for the same reason.
"""
import pytest

from codegen_common import (
    ADAPTIVE_SOLVERS, ALL_EMITTABLE_SOLVERS, PROVIDED_IMPORTS, SYSTEMS,
    external_calls,
)

# One structural variant per solver is enough here: the solver axis is what is
# under test, and the structure/layout axes are already swept per solver by the
# clang matrix.
BASE_OPTS = dict(numeric="double", reductions="unrolled", api="struct")
SHAPES = [dict(structure="hierarchical", layout="compact"),
          dict(structure="flat", layout="compact"),
          dict(structure="hierarchical", layout="library")]


@pytest.mark.parametrize("solver", ALL_EMITTABLE_SOLVERS)
@pytest.mark.parametrize("system", sorted(SYSTEMS))
def test_generates_for_every_solver(system, solver):
    """Every system emits C under every tableau."""
    factory, _ = SYSTEMS[system]
    for shape in SHAPES:
        files = factory().to_c(name="model", solver=solver, **BASE_OPTS, **shape)
        assert files, f"{system}/{solver}/{shape}: produced no files"


@pytest.mark.parametrize("solver", ALL_EMITTABLE_SOLVERS)
@pytest.mark.parametrize("system", sorted(SYSTEMS))
def test_import_contract_holds_for_every_solver(system, solver):
    """The emitted C calls nothing the browser runner cannot provide."""
    factory, _ = SYSTEMS[system]
    files = factory().to_c(name="model", solver=solver, **BASE_OPTS,
                           structure="hierarchical", layout="compact")
    missing = external_calls(files) - PROVIDED_IMPORTS
    assert not missing, (
        f"{system}/{solver}: emitted C calls {sorted(missing)}, which the WASM "
        f"import table does not provide")


@pytest.mark.parametrize("solver", ADAPTIVE_SOLVERS)
def test_adaptive_solvers_emit_the_step_controller(solver):
    """An adaptive tableau must emit the accept/reject machinery, not silently
    fall back to a fixed-step loop — the failure mode that would make an
    adaptive selection look like it worked while integrating at a fixed step."""
    factory, _ = SYSTEMS["ode"]
    src = factory().to_c(name="model", solver=solver, **BASE_OPTS,
                         structure="hierarchical", layout="compact")["model.c"]
    assert "fs_trial_step" in src, f"{solver}: no trial-step kernel emitted"
    assert "fs_h" in src, f"{solver}: carried step size missing from the model"
    header = factory().to_c(name="model", solver=solver, **BASE_OPTS,
                            structure="hierarchical", layout="compact")["model.h"]
    assert "fs_h" in header, f"{solver}: carried step size not in the struct"


@pytest.mark.parametrize("solver", ["rk4", "euler", "ssprk22"])
def test_fixed_step_solvers_emit_no_controller(solver):
    """The converse: a fixed-step tableau must not carry adaptive machinery."""
    factory, _ = SYSTEMS["ode"]
    src = factory().to_c(name="model", solver=solver, **BASE_OPTS,
                         structure="hierarchical", layout="compact")["model.c"]
    assert "fs_trial_step" not in src, f"{solver}: emitted an adaptive kernel"
