// The FMI 3.0 Model-Exchange C wrapper.
//
// Generates `fmu.c`: a thin layer that adapts the struct-API model (the
// `<name>_t` instance plus `model_init` / `model_deriv` / `<name>_get_signal` /
// `<name>_set_signal` emitted by `codegen`) to the FMI 3.0 Model-Exchange entry
// points. It `#include`s the generated `<base>.c` directly so it can call the
// file-static `<name>_deriv` (and `<name>_outputs` through it) in one
// translation unit; the build only compiles `fmu.c`.
//
// The value-reference dispatch is the runtime twin of `vrmap`: signal-space
// references (states, outputs, params) forward to `*_get_signal`/`*_set_signal`;
// derivative references read a `model_deriv` scratch; `TIME_VR` is the clock.

use std::fmt::Write as _;

use crate::codegen::{EventKindInfo, EventLayout};
use crate::ir::schema::Direction;

use super::vrmap::VrLayout;

/// Generate the Model-Exchange wrapper `fmu.c` for a model named `model_name`
/// (the `codegen` C identifier) with the given value-reference layout and
/// instantiation token. `has_jvp` adds `fmi3GetDirectionalDerivative` backed by
/// the analytic `<model_name>_jvp`. `events` drives the FMI event interface
/// (indicators + discrete-state update) over the generated `guard_`/`effect_`
/// functions; `ind_base` is the first event-indicator value reference.
pub fn emit_wrapper(
    model_name: &str,
    src_base: &str,
    vr: &VrLayout,
    instantiation_token: &str,
    has_jvp: bool,
    events: &EventLayout,
    ind_base: u32,
) -> String {
    let model_t = format!("{model_name}_t");
    let get_signal = format!("{model_name}_get_signal");
    let set_signal = format!("{model_name}_set_signal");
    let jvp_fn = format!("{model_name}_jvp");
    // Entry points are prefixed with the model name (issue #34), so the wrapper
    // must call `<name>_init` / `<name>_deriv` / `<name>_outputs`, not the old
    // unprefixed forms.
    let init_fn = format!("{model_name}_init");
    let deriv_fn = format!("{model_name}_deriv");
    let outputs_fn = format!("{model_name}_outputs");

    let n_state = vr.n_state;
    let n_sig = vr.n_sig;
    let n_param = vr.n_param;
    let n_input = vr.n_input;
    let signal_end = vr.n_state + vr.n_sig + vr.n_param; // one past the last signal vr
    let der_base = vr.der_base;
    let der_end = der_base as usize + vr.n_state;
    let time_vr = vr.time_vr;
    let n_event_ind = events.n_indicators();
    let ind_end = ind_base as usize + n_event_ind;
    let input_base = vr.input_base;
    let input_end = input_base as usize + n_input;
    // Time-event firing tolerance, sourced from the central constant (not inline).
    let event_tol = format!("{:?}", crate::constants::FMU_EVENT_TIME_TOL);

    // The body is a fixed template with substituted identifiers; keeping it as
    // one literal makes the generated C easy to read against the spec.
    let subst = |s: &str| {
        s.replace("MODEL_T", &model_t)
            .replace("GET_SIGNAL", &get_signal)
            .replace("SET_SIGNAL", &set_signal)
            .replace("MODEL_INIT", &init_fn)
            .replace("MODEL_DERIV", &deriv_fn)
            .replace("MODEL_JVP", &jvp_fn)
    };
    let mut body = subst(WRAPPER_BODY);
    body.push_str(&emit_event_section(&model_t, &outputs_fn, events, n_sig));
    body.push_str(&emit_input_section(&model_t, n_input));
    if has_jvp {
        body.push_str(&subst(WRAPPER_JVP));
    }

    format!(
        "/* FMI 3.0 Model-Exchange wrapper, generated by fastsim. */\n\
         #include \"fmi3.h\"\n\
         #include \"{src_base}.c\"\n\
         #include <math.h>\n\
         #include <stdlib.h>\n\
         #include <string.h>\n\
         \n\
         #define N_STATE  {n_state}u\n\
         #define N_SIG    {n_sig}u\n\
         #define N_PARAM  {n_param}u\n\
         #define N_INPUT  {n_input}u\n\
         #define SIGNAL_END {signal_end}u\n\
         #define DER_BASE {der_base}u\n\
         #define DER_END  {der_end}u\n\
         #define TIME_VR  {time_vr}u\n\
         #define IND_BASE {ind_base}u\n\
         #define IND_END  {ind_end}u\n\
         #define N_EVENT_IND {n_event_ind}u\n\
         #define INPUT_BASE {input_base}u\n\
         #define INPUT_END  {input_end}u\n\
         #define EVENT_TIME_TOL {event_tol}\n\
         #define INSTANTIATION_TOKEN \"{instantiation_token}\"\n\
         \n\
         /* accessors defined in the generated sections below */\n\
         static double fastsim_event_indicator({model_t}* m, size_t i);\n\
         static double fastsim_get_input(const {model_t}* m, size_t i);\n\
         static void fastsim_set_input({model_t}* m, size_t i, double v);\n\
         \n\
         {body}"
    )
}

/// The external-input accessors, generated so the static `GetFloat64`/`SetFloat64`
/// can route input value references to `m->u[]` without referencing the field
/// when there are no inputs (a closed model has no `u[]`).
fn emit_input_section(model_t: &str, n_input: usize) -> String {
    if n_input == 0 {
        return format!(
            "\nstatic double fastsim_get_input(const {model_t}* m, size_t i) {{ (void)m; (void)i; return 0.0; }}\n\
             static void fastsim_set_input({model_t}* m, size_t i, double v) {{ (void)m; (void)i; (void)v; }}\n"
        );
    }
    format!(
        "\nstatic double fastsim_get_input(const {model_t}* m, size_t i) {{ return m->u[i]; }}\n\
         static void fastsim_set_input({model_t}* m, size_t i, double v) {{ m->u[i] = v; }}\n"
    )
}

/// The FMI event interface, generated from the event layout: the indicator
/// accessor, `fmi3GetEventIndicators` / `fmi3GetNumberOfEventIndicators`,
/// `fmi3CompletedIntegratorStep` (records the previous indicator values), and
/// `fmi3UpdateDiscreteStates` (applies due time events + crossed state events
/// and reports the next event time). With no events these are correct stubs.
fn emit_event_section(model_t: &str, outputs_fn: &str, events: &EventLayout, n_sig: usize) -> String {
    let refresh = if n_sig > 0 { format!("    {outputs_fn}(m);\n") } else { String::new() };
    let refresh = refresh.as_str();
    let mut s = String::new();

    // --- indicator accessor: guard value by index ---
    let inds: Vec<&str> = events.indicators().map(|e| e.suffix.as_str()).collect();
    let _ = write!(s, "\nstatic double fastsim_event_indicator({model_t}* m, size_t i) {{\n");
    if inds.is_empty() {
        s.push_str("    (void)m; (void)i; return 0.0;\n");
    } else {
        s.push_str(refresh);
        s.push_str("    switch (i) {\n");
        for (i, suf) in inds.iter().enumerate() {
            let _ = writeln!(s, "        case {i}: return guard_{suf}(m);");
        }
        s.push_str("        default: return 0.0;\n    }\n");
    }
    s.push_str("}\n");

    // --- fmi3GetNumberOfEventIndicators / fmi3GetEventIndicators ---
    let _ = write!(
        s,
        "\nFMI3_Export fmi3Status fmi3GetNumberOfEventIndicators(fmi3Instance instance, size_t* nEventIndicators) {{\n\
         \x20   (void)instance;\n\
         \x20   if (nEventIndicators) *nEventIndicators = N_EVENT_IND;\n\
         \x20   return fmi3OK;\n}}\n"
    );
    let _ = write!(
        s,
        "\nFMI3_Export fmi3Status fmi3GetEventIndicators(fmi3Instance instance, fmi3Float64 eventIndicators[], size_t nEventIndicators) {{\n\
         \x20   {model_t}* m = ({model_t}*)instance;\n\
         \x20   if (!m || nEventIndicators != N_EVENT_IND) return fmi3Error;\n\
         \x20   for (size_t i = 0; i < N_EVENT_IND; i++) eventIndicators[i] = fastsim_event_indicator(m, i);\n\
         \x20   return fmi3OK;\n}}\n"
    );

    // --- fmi3CompletedIntegratorStep: record previous indicator values ---
    let _ = write!(
        s,
        "\nFMI3_Export fmi3Status fmi3CompletedIntegratorStep(\n\
         \x20       fmi3Instance instance, fmi3Boolean noSetFMUStatePriorToCurrentPoint,\n\
         \x20       fmi3Boolean* enterEventMode, fmi3Boolean* terminateSimulation) {{\n\
         \x20   (void)noSetFMUStatePriorToCurrentPoint;\n\
         \x20   {model_t}* m = ({model_t}*)instance;\n\
         \x20   if (!m) return fmi3Error;\n"
    );
    if !inds.is_empty() {
        s.push_str(refresh);
        for suf in &inds {
            let _ = writeln!(s, "    m->prev_{suf} = guard_{suf}(m); m->init_{suf} = 1;");
        }
    }
    s.push_str(
        "    if (enterEventMode) *enterEventMode = fmi3False;\n\
         \x20   if (terminateSimulation) *terminateSimulation = fmi3False;\n\
         \x20   return fmi3OK;\n}\n",
    );

    // --- fmi3UpdateDiscreteStates: apply crossed/due events, report next time ---
    let _ = write!(
        s,
        "\nFMI3_Export fmi3Status fmi3UpdateDiscreteStates(\n\
         \x20       fmi3Instance instance, fmi3Boolean* discreteStatesNeedUpdate, fmi3Boolean* terminateSimulation,\n\
         \x20       fmi3Boolean* nominalsOfContinuousStatesChanged, fmi3Boolean* valuesOfContinuousStatesChanged,\n\
         \x20       fmi3Boolean* nextEventTimeDefined, fmi3Float64* nextEventTime) {{\n\
         \x20   {model_t}* m = ({model_t}*)instance;\n\
         \x20   if (!m) return fmi3Error;\n\
         \x20   int changed = 0; double next_t = INFINITY; int next_def = 0;\n"
    );
    s.push_str(refresh);
    for ev in &events.events {
        let suf = &ev.suffix;
        // Only a state-modifying effect flags `valuesOfContinuousStatesChanged`;
        // a memory-only effect changes discrete state, not the continuous state.
        let chg = if ev.modifies_state { "changed = 1; " } else { "" };
        match &ev.kind {
            EventKindInfo::ZeroCross { direction } => {
                let cond = match direction {
                    Direction::Both => format!("cur * m->prev_{suf} < 0.0"),
                    Direction::Rising => format!("cur > 0.0 && m->prev_{suf} <= 0.0"),
                    Direction::Falling => format!("cur < 0.0 && m->prev_{suf} >= 0.0"),
                };
                let _ = writeln!(
                    s,
                    "    {{ double cur = guard_{suf}(m); if (m->init_{suf} && ({cond})) {{ effect_{suf}(m); {chg}}} m->prev_{suf} = guard_{suf}(m); }}"
                );
            }
            EventKindInfo::Condition => {
                let _ = writeln!(
                    s,
                    "    {{ double cur = guard_{suf}(m); if (cur != 0.0 && (!m->init_{suf} || m->prev_{suf} == 0.0)) {{ effect_{suf}(m); {chg}}} m->prev_{suf} = cur; m->init_{suf} = 1; }}"
                );
            }
            EventKindInfo::Periodic { period, phase } => {
                // Next scheduled time recomputed as `phase + k*period` (matches
                // the C-codegen struct field `k_<suf>` and the runtime scheduler).
                let _ = write!(
                    s,
                    "    while (m->time + EVENT_TIME_TOL >= {phase:?} + (double)m->k_{suf} * {period:?}) {{ effect_{suf}(m); m->k_{suf}++; {chg}}}\n\
                     \x20   {{ double nt_{suf} = {phase:?} + (double)m->k_{suf} * {period:?}; if (nt_{suf} < next_t) next_t = nt_{suf}; }}\n\
                     \x20   next_def = 1;\n"
                );
            }
            EventKindInfo::Fixed { times } => {
                let arr = times.iter().map(|t| format!("{t:?}")).collect::<Vec<_>>().join(", ");
                let n = times.len();
                let _ = write!(
                    s,
                    "    {{ static const double times_{suf}[] = {{ {arr} }};\n\
                     \x20     while (m->fi_{suf} < {n} && m->time + EVENT_TIME_TOL >= times_{suf}[m->fi_{suf}]) {{ effect_{suf}(m); m->fi_{suf}++; {chg}}}\n\
                     \x20     if (m->fi_{suf} < {n}) {{ if (times_{suf}[m->fi_{suf}] < next_t) next_t = times_{suf}[m->fi_{suf}]; next_def = 1; }} }}\n"
                );
            }
        }
    }
    s.push_str(
        "    if (discreteStatesNeedUpdate) *discreteStatesNeedUpdate = fmi3False;\n\
         \x20   if (terminateSimulation) *terminateSimulation = fmi3False;\n\
         \x20   if (nominalsOfContinuousStatesChanged) *nominalsOfContinuousStatesChanged = fmi3False;\n\
         \x20   if (valuesOfContinuousStatesChanged) *valuesOfContinuousStatesChanged = changed ? fmi3True : fmi3False;\n\
         \x20   if (nextEventTimeDefined) *nextEventTimeDefined = next_def ? fmi3True : fmi3False;\n\
         \x20   if (nextEventTime) *nextEventTime = next_t;\n\
         \x20   return fmi3OK;\n}\n",
    );

    s
}

/// The wrapper function bodies. `MODEL_T` / `GET_SIGNAL` / `SET_SIGNAL` are
/// substituted with the model's struct type and accessor names.
const WRAPPER_BODY: &str = r##"FMI3_Export const char* fmi3GetVersion(void) { return "3.0"; }

FMI3_Export fmi3Instance fmi3InstantiateModelExchange(
        fmi3String instanceName, fmi3String instantiationToken, fmi3String resourcePath,
        fmi3Boolean visible, fmi3Boolean loggingOn,
        fmi3InstanceEnvironment instanceEnvironment, fmi3LogMessageCallback logMessage) {
    (void)instanceName; (void)resourcePath; (void)visible; (void)loggingOn;
    (void)instanceEnvironment; (void)logMessage;
    if (!instantiationToken || strcmp(instantiationToken, INSTANTIATION_TOKEN) != 0) return NULL;
    MODEL_T* m = (MODEL_T*)malloc(sizeof(MODEL_T));
    if (m) MODEL_INIT(m);
    return (fmi3Instance)m;
}

FMI3_Export void fmi3FreeInstance(fmi3Instance instance) { free(instance); }

FMI3_Export fmi3Status fmi3EnterInitializationMode(
        fmi3Instance instance, fmi3Boolean toleranceDefined, fmi3Float64 tolerance,
        fmi3Float64 startTime, fmi3Boolean stopTimeDefined, fmi3Float64 stopTime) {
    (void)toleranceDefined; (void)tolerance; (void)stopTimeDefined; (void)stopTime;
    MODEL_T* m = (MODEL_T*)instance;
    if (!m) return fmi3Error;
    m->time = startTime;
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3ExitInitializationMode(fmi3Instance instance) { (void)instance; return fmi3OK; }
FMI3_Export fmi3Status fmi3EnterEventMode(fmi3Instance instance) { (void)instance; return fmi3OK; }
FMI3_Export fmi3Status fmi3Terminate(fmi3Instance instance) { (void)instance; return fmi3OK; }

FMI3_Export fmi3Status fmi3Reset(fmi3Instance instance) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m) return fmi3Error;
    MODEL_INIT(m);
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3SetDebugLogging(
        fmi3Instance instance, fmi3Boolean loggingOn, size_t nCategories, const fmi3String categories[]) {
    (void)instance; (void)loggingOn; (void)nCategories; (void)categories;
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3EnterContinuousTimeMode(fmi3Instance instance) { (void)instance; return fmi3OK; }

FMI3_Export fmi3Status fmi3SetTime(fmi3Instance instance, fmi3Float64 time) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m) return fmi3Error;
    m->time = time;
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3SetContinuousStates(
        fmi3Instance instance, const fmi3Float64 continuousStates[], size_t nContinuousStates) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m || nContinuousStates != N_STATE) return fmi3Error;
    for (size_t i = 0; i < N_STATE; i++) m->x[i] = continuousStates[i];
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3GetContinuousStates(
        fmi3Instance instance, fmi3Float64 continuousStates[], size_t nContinuousStates) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m || nContinuousStates != N_STATE) return fmi3Error;
    for (size_t i = 0; i < N_STATE; i++) continuousStates[i] = m->x[i];
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3GetContinuousStateDerivatives(
        fmi3Instance instance, fmi3Float64 derivatives[], size_t nContinuousStates) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m || nContinuousStates != N_STATE) return fmi3Error;
    MODEL_DERIV(m, derivatives);
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3GetNominalsOfContinuousStates(
        fmi3Instance instance, fmi3Float64 nominals[], size_t nContinuousStates) {
    (void)instance;
    if (nContinuousStates != N_STATE) return fmi3Error;
    for (size_t i = 0; i < N_STATE; i++) nominals[i] = 1.0;
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3GetNumberOfContinuousStates(fmi3Instance instance, size_t* nContinuousStates) {
    (void)instance;
    if (nContinuousStates) *nContinuousStates = N_STATE;
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3GetFloat64(
        fmi3Instance instance, const fmi3ValueReference valueReferences[], size_t nValueReferences,
        fmi3Float64 values[], size_t nValues) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m || nValueReferences != nValues) return fmi3Error;
    fmi3Float64 dxbuf[N_STATE];
    int have_deriv = 0;
    for (size_t k = 0; k < nValueReferences; k++) {
        fmi3ValueReference r = valueReferences[k];
        if (r == TIME_VR) {
            values[k] = m->time;
        } else if (r < SIGNAL_END) {
            values[k] = GET_SIGNAL(m, (uint16_t)r);
        } else if (r >= DER_BASE && r < DER_END) {
            if (!have_deriv) { MODEL_DERIV(m, dxbuf); have_deriv = 1; }
            values[k] = dxbuf[r - DER_BASE];
        } else if (r >= IND_BASE && r < IND_END) {
            values[k] = fastsim_event_indicator(m, r - IND_BASE);
        } else if (r >= INPUT_BASE && r < INPUT_END) {
            values[k] = fastsim_get_input(m, r - INPUT_BASE);
        } else {
            return fmi3Error;
        }
    }
    return fmi3OK;
}

FMI3_Export fmi3Status fmi3SetFloat64(
        fmi3Instance instance, const fmi3ValueReference valueReferences[], size_t nValueReferences,
        const fmi3Float64 values[], size_t nValues) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m || nValueReferences != nValues) return fmi3Error;
    for (size_t k = 0; k < nValueReferences; k++) {
        fmi3ValueReference r = valueReferences[k];
        if (r == TIME_VR) {
            m->time = values[k];
        } else if (r < SIGNAL_END) {
            if (SET_SIGNAL(m, (uint16_t)r, values[k]) != 0) return fmi3Error;
        } else if (r >= INPUT_BASE && r < INPUT_END) {
            fastsim_set_input(m, r - INPUT_BASE, values[k]);
        } else {
            return fmi3Error;
        }
    }
    return fmi3OK;
}
"##;

/// The directional-derivative entry point, appended only when the model has an
/// analytic `MODEL_JVP`. Computes `sensitivity = (d(unknowns)/d(knowns)) . seed`
/// for the full continuous set: `knowns` ∈ states ∪ inputs ∪ parameters and
/// `unknowns` ∈ state-derivatives ∪ outputs. The seed is scattered into the
/// per-class seed vectors, the exact forward-AD JVP is evaluated once, and the
/// requested tangents are gathered from `d_dxdt` (derivatives) / `d_sig`
/// (outputs). The `+1` paddings avoid zero-length arrays when a class is empty.
const WRAPPER_JVP: &str = r##"
FMI3_Export fmi3Status fmi3GetDirectionalDerivative(
        fmi3Instance instance,
        const fmi3ValueReference unknowns[], size_t nUnknowns,
        const fmi3ValueReference knowns[], size_t nKnowns,
        const fmi3Float64 seed[], size_t nSeed,
        fmi3Float64 sensitivity[], size_t nSensitivity) {
    MODEL_T* m = (MODEL_T*)instance;
    if (!m || nSeed != nKnowns || nSensitivity != nUnknowns) return fmi3Error;
    fmi3Float64 x_seed[N_STATE];
    fmi3Float64 u_seed[N_INPUT + 1];
    fmi3Float64 p_seed[N_PARAM + 1];
    fmi3Float64 d_sig[N_SIG + 1];
    fmi3Float64 d_dxdt[N_STATE];
    for (size_t i = 0; i < N_STATE; i++) x_seed[i] = 0.0;
    for (size_t i = 0; i < N_INPUT; i++) u_seed[i] = 0.0;
    for (size_t i = 0; i < N_PARAM; i++) p_seed[i] = 0.0;
    for (size_t k = 0; k < nKnowns; k++) {
        fmi3ValueReference r = knowns[k];
        if (r < N_STATE) {
            x_seed[r] = seed[k];
        } else if (r >= N_STATE + N_SIG && r < SIGNAL_END) {
            p_seed[r - (N_STATE + N_SIG)] = seed[k];
        } else if (r >= INPUT_BASE && r < INPUT_END) {
            u_seed[r - INPUT_BASE] = seed[k];
        } else {
            return fmi3Error;   /* knowns must be states, parameters or inputs */
        }
    }
    MODEL_JVP(m, x_seed, u_seed, p_seed, d_sig, d_dxdt);
    for (size_t u = 0; u < nUnknowns; u++) {
        fmi3ValueReference r = unknowns[u];
        if (r >= DER_BASE && r < DER_END) {
            sensitivity[u] = d_dxdt[r - DER_BASE];
        } else if (r >= N_STATE && r < N_STATE + N_SIG) {
            sensitivity[u] = d_sig[r - N_STATE];
        } else {
            return fmi3Error;   /* unknowns must be state derivatives or outputs */
        }
    }
    return fmi3OK;
}
"##;
