#!/usr/bin/env python
"""Cross-check FastSim's FMI 3.0 importer against FMUs built by other tools.

The Modelica Association's Reference-FMUs are the corpus FastSim's own test
suite runs on, but they are produced by the same project that writes the
standard. This script closes that gap by importing FMI 3.0 FMUs generated by an
unrelated exporter and comparing FastSim's results, element by element, against
both FMPy and a closed form.

It is the reproducible form of the interoperability claim: run it and read the
table, rather than taking the claim on trust.

Corpus
------
`PMSFIT/FMI30TestFMUs` (MPL-2.0), a set of non-normative FMI 3.0 test FMUs from
PMSF. They are Co-Simulation only, declare `hasEventMode="false"`, and cover the
scalar and the array cases of every variable type. Build them with::

    git clone https://github.com/PMSFIT/FMI30TestFMUs
    cd FMI30TestFMUs && cmake -B build -G "MinGW Makefiles" && cmake --build build

then point ``--fmu-dir`` at the resulting ``build`` directory. Prebuilt CI
artifacts exist but expire.

The three FMUs compute ``Float64Output = Float64Parameter * Float64Input``
element by element. Driving the parameters and the inputs with two *different*
sets of distinct per-element values makes the check sensitive to element order:
a transposed or shifted flattening shows up as a mismatch, which a uniform
parameter would hide.

These FMUs never apply their own declared `start` attributes internally — they
`calloc` their arrays — so both importers read zeros unless the values are
pushed in explicitly. That is what ``start_values`` does here, and FMPy agreeing
on the zeros is itself part of the evidence.

Usage
-----
    python scripts/verify_third_party_fmus.py --fmu-dir <FMI30TestFMUs/build>
        [--fmpy-python <interpreter with fmpy installed>]

Exits non-zero on any mismatch.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

import numpy as np

import fastsim
from fastsim.blocks import Constant, CoSimulationFMU

# Variable types that carry no meaningful f64 value and so are not block ports.
NON_PORT = {"String", "Binary", "Clock"}

# name -> number of Float64Output elements
CASES = {"SimpleVariableTest": 1, "SimpleArrayTest": 6, "DynamicArrayTest": 12}


def port_range(fmu_path: Path, var_name: str, kind: str) -> tuple[int, int]:
    """First port index and element count of `var_name`, as FastSim numbers them.

    FastSim gives every numeric variable a port, one per array element — inputs
    in declaration order, outputs in `<ModelStructure>` order. Recomputing the
    offset from the XML keeps the comparison independent of how many other
    variables the FMU declares, and independently reproduces the mapping the
    importer builds.
    """
    root = ET.fromstring(zipfile.ZipFile(fmu_path).read("modelDescription.xml"))
    model_vars = list(root.find("ModelVariables"))
    by_vr = {v.get("valueReference"): v for v in model_vars}
    sizes = {
        v.get("valueReference"): int(v.get("start"))
        for v in model_vars
        if v.tag == "UInt64" and v.get("start")
    }

    def n_values(v) -> int:
        total = 1
        for d in v.findall("Dimension"):
            total *= int(d.get("start") or sizes[d.get("valueReference")])
        return total

    if kind == "input":
        ordered = [v for v in model_vars if v.get("causality") == "input"]
    else:
        ordered = [
            by_vr[o.get("valueReference")]
            for o in root.find("ModelStructure").findall("Output")
        ]

    idx = 0
    for v in ordered:
        if v.tag in NON_PORT:
            continue
        if v.get("name") == var_name:
            return idx, n_values(v)
        idx += n_values(v)
    raise KeyError(f"{var_name} is not an {kind} of {fmu_path.name}")


def run_fastsim(fmu_path: Path, params: np.ndarray, u: np.ndarray) -> np.ndarray:
    """Import the FMU as a FastSim block, drive its inputs, read its outputs."""
    fmu = CoSimulationFMU(
        str(fmu_path),
        instance_name=fmu_path.stem,
        dt=0.01,
        start_values={"Float64Parameter": list(params)},
    )
    in_off, in_n = port_range(fmu_path, "Float64Input", "input")
    out_off, out_n = port_range(fmu_path, "Float64Output", "output")
    if (in_n, out_n) != (len(u), len(params)):
        raise AssertionError(
            f"{fmu_path.stem}: expected {len(u)} input and {len(params)} output "
            f"elements, the FMU declares {in_n} and {out_n}"
        )

    sources = [Constant(v) for v in u]
    conns = [fastsim.Connection(s, fmu[in_off + i]) for i, s in enumerate(sources)]
    sim = fastsim.Simulation([fmu, *sources], conns, dt=0.01, log=False)
    sim.run(0.1)
    return np.array([fmu.outputs[out_off + i] for i in range(out_n)])


def run_fmpy(
    fmpy_python: str, fmu_path: Path, params: np.ndarray, u: np.ndarray
) -> np.ndarray:
    """Same FMU under FMPy, in a separate interpreter, flattened row-major.

    FMPy usually lives in a different environment than FastSim, so it is driven
    out of process and answers over stdout as JSON.
    """
    # FMPy takes a bare number for a scalar variable and a list only for an
    # array; FastSim accepts either and broadcasts.
    def as_start(values: np.ndarray):
        return float(values[0]) if len(values) == 1 else list(values)

    script = f"""
import numpy as np, fmpy, json
r = fmpy.simulate_fmu(
    r"{fmu_path}",
    stop_time=0.1,
    start_values={{
        "Float64Parameter": {as_start(params)!r},
        "Float64Input": {as_start(u)!r},
    }},
    output=["Float64Output"],
)
print(json.dumps(np.asarray(r[-1]["Float64Output"]).ravel().tolist()))
"""
    out = subprocess.run([fmpy_python, "-c", script], capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(f"FMPy failed for {fmu_path.name}:\n{out.stderr[-800:]}")
    return np.array(json.loads(out.stdout.strip().splitlines()[-1]))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--fmu-dir",
        type=Path,
        required=True,
        help="build directory of PMSFIT/FMI30TestFMUs",
    )
    ap.add_argument(
        "--fmpy-python",
        default=sys.executable,
        help="interpreter with fmpy installed (default: this one)",
    )
    args = ap.parse_args()

    failures = []
    for name, n in CASES.items():
        fmu_path = args.fmu_dir / name / f"{name}.fmu"
        if not fmu_path.is_file():
            print(f"{name:20s} SKIP  not found at {fmu_path}")
            continue

        # Two distinct sets, so the product is order-sensitive.
        params = np.arange(1.0, n + 1.0)
        u = np.arange(10.0, 10.0 * (n + 1), 10.0)
        analytic = params * u

        got = run_fastsim(fmu_path, params, u)
        ref = run_fmpy(args.fmpy_python, fmu_path, params, u)
        e_fmpy = float(np.max(np.abs(got - ref)))
        e_ana = float(np.max(np.abs(got - analytic)))
        ok = e_fmpy == 0.0 and e_ana == 0.0

        print(f"{name}  ({n} element{'s' if n > 1 else ''})")
        print(f"  parameter          {params}")
        print(f"  input              {u}")
        print(f"  analytic           {analytic}")
        print(f"  fastsim            {got}")
        print(f"  fmpy               {ref}")
        print(f"  |fastsim - fmpy|     {e_fmpy:.3e}")
        print(f"  |fastsim - analytic| {e_ana:.3e}")
        print(f"  {'PASS' if ok else 'FAIL'}\n")
        if not ok:
            failures.append(name)

    if failures:
        print(f"MISMATCH in: {', '.join(failures)}")
        return 1
    print("all element-wise checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
