# Auto-generated by scripts/gen_shims.py — DO NOT EDIT BY HAND.
# Regenerate after `maturin develop` when the API changes.

# fastsim.events — Drop-in replacement for pathsim.events

from fastsim._fastsim import (
    ZeroCrossing as _ZeroCrossing,
    ZeroCrossingUp as _ZeroCrossingUp,
    ZeroCrossingDown as _ZeroCrossingDown,
    Schedule as _Schedule,
    ScheduleList as _ScheduleList,
    Condition as _Condition,
)

class ZeroCrossing(_ZeroCrossing):
    """
    Event that triggers when an event function crosses zero in either
    direction. The exact crossing time is located by root-finding and the
    attached action callback is invoked there. Drop-in compatible with
    pathsim.events.ZeroCrossing.
    """

class ZeroCrossingUp(_ZeroCrossingUp):
    """
    Event that triggers only on an upward (negative-to-positive) zero
    crossing of the event function. Drop-in compatible with
    pathsim.events.ZeroCrossingUp.
    """

class ZeroCrossingDown(_ZeroCrossingDown):
    """
    Event that triggers only on a downward (positive-to-negative) zero
    crossing of the event function. Drop-in compatible with
    pathsim.events.ZeroCrossingDown.
    """

class Schedule(_Schedule):
    """
    Event that triggers on a periodic time schedule (a fixed start time and
    repeating interval), invoking its action callback at each occurrence.
    Drop-in compatible with pathsim.events.Schedule.
    """

class ScheduleList(_ScheduleList):
    """
    Event that triggers at an explicit list of scheduled times, invoking its
    action callback at each. Drop-in compatible with
    pathsim.events.ScheduleList.
    """

class Condition(_Condition):
    """
    Event that triggers when a user-supplied boolean condition becomes true,
    invoking its action callback. Useful for state-dependent logic that is not
    a simple zero crossing. Drop-in compatible with pathsim.events.Condition.
    """
